# Netlify configuration
[build]
  base = ""                 # Root directory (where netlify.toml is located)
  publish = "client/public" # Directory with your frontend files
  command = ""              # Add a build command if needed

# Redirect API requests to your Azure backend
[[redirects]]
  from = "/api/*"
  to = "https://book-listing-software-web-app-b9bmf6b3eqgeggee.australiaeast-01.azurewebsites.net/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
