/**
 * Valid eBay Topics for Australia
 * Extracted from server.js for reuse across the application
 */

const VALID_EBAY_TOPICS = [
  "3D Art", "3D Design", "ABCs/Numbers", "Abstract Art", "Abstract Photography", 
  "Abuse", "Accounting", "Action Movies", "Activity Holiday", "Addiction", 
  "Administration", "Administrative Law", "Adoption", "African Americans", 
  "African Cuisine", "Afterlife", "Agents", "Aging", "Agriculture", "Aircraft", 
  "Air Force", "Airplanes", "Alcohol", "Alternative Belief Systems", "Alternative Health", 
  "Alternative Medicine", "Alternative Therapies", "Amateur Radio", "American Cuisine", 
  "American Football", "American History", "American Indian Wars", "American Revolution", 
  "American Revolutionary War", "Ammunition", "Amphibians", "Anatomy", "Ancient World", 
  "Ancillary Services", "Anecdotes", "Anesthesiology", "Angels", "Animal Care", 
  "Animal Husbandry", "Animal Psychology", "Animal Sports", "Animal Training", 
  "Animal Welfare", "Animation", "Anthology", "Anthropology", "Antiques", "Apple", 
  "Applied Technology", "Archaeology", "Archery", "Architectural Photography", 
  "Architecture", "Army", "Art Criticism", "Art Déco", "Art History", "Art Instruction", 
  "Artists", "Art Nouveau", "Art Theory", "Asian Cuisine", "Assertiveness", "Astrology", 
  "Astronomy", "Aura Soma", "Australasian Cuisine", "Australia", "Australian Cuisine", 
  "Australian History", "Austrian Cuisine", "Autobiography", "Automobiles", "Avant Garde", 
  "Baking", "Balcony", "Balkan Cuisine", "Ballet", "Ball Games", "Baptists", "Barbecue", 
  "Baroque", "Baseball", "Basketball", "Bathroom", "BDSM", "Beauty", "Beer", "Beliefs", 
  "Bereavement", "Beverages", "Bible", "Bicycles", "Bilingual", "Biochemistry", "Biology", 
  "Birds", "Birds of Prey", "Birdwatching", "Blues", "Board Games", "Boating", "Bodybuilding", 
  "Bonsai", "Books", "Botany", "Boxing", "Boys' Interest", "Brain Teasers", "Brazilian Cuisine", 
  "Breeding", "Bridges", "British Cuisine", "British Wars", "Broadway", "Buddhism", "Budgies", 
  "Building", "Building Plans", "Building Trade", "Business Analysis", "Business Ethics", 
  "Business Software", "Byzantine Architecture", "Cactuses", "Calligraphy", "Camping", 
  "Canadian Cuisine", "Canning", "Card Games", "Careers", "Caribbean Cuisine", "Cars", 
  "Cartooning", "Castles", "Catering Trade", "Catholicism", "Cats", "Celebrity Chef", 
  "Celtic Paganism", "Central American Cuisine", "Central European Cuisine", "Ceramics", 
  "Certification", "Charts", "Chemistry", "Chess", "Chickens", "Childbirth", "Chinese Cuisine", 
  "Christian History", "Christianity", "Christmas", "Church Buildings", "Cities", "Citizenship", 
  "Civil Engineering", "Civil War", "Classical Music", "Classic Cars", "Classicism", 
  "Classic Literature", "Classic Modern Art", "Classic Recipes", "Clean Eating", "Climbing", 
  "Clocks", "Clubs", "Coaching", "Coast Guard", "Cocktails", "Coins", "Cold Meals", 
  "Collectibles", "Colonialism", "Combat", "Combat Sports", "Comedies", "Comic Books", 
  "Coming of Age", "Commercial Art", "Commercial Forest", "Commercial Policy", 
  "Commercial Vehicle", "Commune", "Communications", "Communication Skills", 
  "Comparative Religion", "Computer Hardware", "Computer Security", "Computing", 
  "Connect the Dots", "Connoisseur", "Constitution", "Constitutional Law", "Construction", 
  "Constructivism", "Consumer Electronics", "Consumer Issues", "Contemporary", 
  "Contemporary Art", "Contemporary Folk Music", "Contemporary History", "Cooking", 
  "Cooking by Ingredient", "Cooking for Children", "Cooking for One", "Cooking with Gadgets", 
  "Coping with Illness", "Cosmology", "Costume", "Country Music", "Crafts", 
  "Crafts for Children", "Creativity", "Cricket", "Crime", "Crises", "Criticism", 
  "Crocheting", "Cross Stitch", "Crosswords", "Culinary Arts", "Culinary Techniques", 
  "Cult Movies", "Cultural History", "Cultural Studies", "Culture", "Current Affairs", 
  "Cycling", "Cycling Tours", "Dance", "Databases", "Death", "Decluttering", "Decorating", 
  "Decorative Art", "Demons", "Dental Nursing", "Dentistry", "Design", "Desktop Publishing", 
  "Desserts", "Detective Stories", "Devotions", "Diabetic Cooking", "Dice Games", "Dieting", 
  "Digital Lifestyle", "Digital Media", "Digital Photography", "Dinosaurs", "Dips", 
  "Disability Sports", "Diseases", "Disney", "Divination", "Divorce", "Doctors", 
  "Documentaries", "Dogs", "Do-It-Yourself", "Dolls", "Dramas", "Drawing", 
  "Dream Interpretation", "Drinks", "Driving", "Drugs", "Ducks", "Earth Sciences", 
  "Easter", "Eastern European Cuisine", "Easy Meals", "Ecological Construction", 
  "E-Commerce", "Economic History", "Economic Strategy", "Ecumenism", "Education", 
  "Electrical Engineering", "Electrical Installation", "Electronic Music", "Electronics", 
  "Embroidery", "Emotional Intelligence", "Employment References", "Energy Technology", 
  "English Legal System", "Enjoyment", "Entertainment", "Entrepreneurship", "Environment", 
  "Environmental Engineering", "Environmental Issues", "Environmental Protection", 
  "Episcopal Church", "Equestrian Sports", "Erotic Photography", "Esotericism", 
  "Espionage", "Ethnicity", "Ethnic Studies", "Etiquette", "EU Law", "European Championship", 
  "European Cuisine", "Exercise", "Exhibitions", "Exploration", "Extreme Sports", 
  "Family History", "Family Law", "Family Life", "Family Therapy", "Fan Fiction", 
  "Farm Animals", "Farmed Poultry", "Farm Holidays", "Fashion Design", "Fashion Photography", 
  "Fasting", "Felting", "Feng Shui", "Field Flowers", "Field Hockey", "Field Sports", 
  "Film", "Film Noir", "Fine Arts", "First Aid", "First Love", "First Names", "Fish", 
  "Fishing", "Fitness", "Floristics", "Fly Fishing", "Flying", "Food", "Food Writing", 
  "Foreign Militaries", "Forensics", "Fortresses", "Fortune-Telling", "French Cuisine", 
  "Freshwater Fish", "Freshwater Fishing", "Friendship", "Fringe Sciences", "Fruit", 
  "Fruit-Bearing Trees", "Functionalism", "Furniture", "Futurism", "Gambling", 
  "Game Programming", "Games", "Game Theory", "Garden Flowers", "Gardening", "Gardens", 
  "Geese", "Gender Studies", "Genealogy", "General Politics", "General Thriller", 
  "German Cuisine", "Germanic Paganism", "Ghosts", "Girls' Interest", "Glass", 
  "Global Politics", "Gluten-Free Cooking", "Goats", "Golf", "Gourmet", "Government", 
  "Graphical Media", "Graphic Arts", "Graphic Design", "Greek", "Greek Architecture", 
  "Greek Wars", "Greenhouses", "Grief", "Grooming", "Gulf War", "Gymnastics", "Halloween", 
  "Hamsters", "Health", "Heavy Metal", "Hedges", "Heimat", "Heimatfilme", "Helicopters", 
  "Help", "Herbary", "Herbs", "Hiking", "Hinduism", "Hip Hop", "Historic Figures", 
  "History of Ideas", "History of Technology", "Hobbies", "Holidays", "Holidays for Women", 
  "Home Decor", "Homeopathy", "Homeschooling", "Horse Riding", "Horses", "Horticulture", 
  "House Plants", "Houses", "HR", "Hundertwasser", "Hunting", "Hymns", "Ice Hockey", 
  "Ice Skating", "Ikebana", "Illustration", "Image Processing", "Indian Cuisine", 
  "Indoor Games", "Industrial Building", "Industrial Chemistry", "Industry", "Infographics", 
  "Inheritance", "Inspirational Works", "Insurance", "Interior Design", "International Cuisine", 
  "International Law", "International Politics", "International Relations", "Internet", 
  "Inventions", "Investment", "Iranian Cuisine", "Iraq War", "Irish Cuisine", "Islam", 
  "Israeli Cuisine", "IT", "Italian Cuisine", "Japanese Cuisine", "Jazz", "Jesus Christ", 
  "Jewellery", "Job Applications", "Job Hunting", "Job Interviews", "Jogging", "Judaism", 
  "Kakuro", "Kindergarten", "King Arthur", "Kitchen", "Kitchen Appliances", "Knitting", 
  "Korean Cuisine", "Korean War", "Landscape Photography", "Landscaping", "Languages", 
  "Language Skills", "Last Will and Testament", "Latin American Cuisine", "Learning to Read", 
  "Legal Thriller", "Leisure", "LGBT Studies", "Life Crisis", "Life Management", 
  "Life Partnership", "Lifestyle", "Linguistics", "Linux", "Literary Criticism", 
  "Literary Theory", "Literature", "Liturgical Year", "Local History", "Local Interest", 
  "Logic", "Love", "Low-Carb Cooking", "Lutheranism", "Mac", "Magic Tricks", 
  "Management Techniques", "Managing Conflict", "Manners", "Marathon", "Marines", 
  "Maritime History", "Marketing", "Marriage", "Martial Arts", "Massage", "Maternity", 
  "Mathematics", "Mazes", "Mechanical Engineering", "Media", "Medical Nursing", 
  "Medical Services", "Medicine", "Meditation", "Memoir", "Memorials", "Memory Improvement", 
  "Men's Fiction", "Mental Exercise", "Mental Health", "Mental Illness", "Metaphysical", 
  "Meteorology", "Methodism", "Mexican Cuisine", "Mice", "Microsoft", "Middle Ages", 
  "Middle Class", "Middle Eastern Cuisine", "Military History", "Mind", "Minority Studies", 
  "Model Railroads", "Modern Art", "Modern History", "Modern Literature", "Money", 
  "Monsters", "Mormons", "Moroccan Cuisine", "Motorcycles", "Motor Sports", "Motor Vehicles", 
  "Mountaineering", "Movies", "MS Office", "Museum Building", "Museums", "Music", 
  "Musical Instruments", "Musicals", "Music of Latin America", "Napkin Decoupage", 
  "Napoleonic Wars", "National Cooking", "National Guard", "National Law", "Native Americans", 
  "Natural Disasters", "Natural History", "Natural Materials", "Natural Medicine", "Nature", 
  "Navy", "Needlepoint", "Needlework", "Negotiating", "Neopaganism", "Network", "Networking", 
  "Neuro-Linguistic Programming", "New Age", "New Wave", "Nobility", "North African Cuisine", 
  "North American Cuisine", "North European Cuisine", "Number Puzzles", "Numismatics", 
  "Nursing", "Nutrition", "Occultism", "Ocean", "Oceanian Cuisine", "Offshore Sportfishing", 
  "Olympic Games", "Operating Systems", "Opinion of the People", "Optical Illusions", 
  "Origami", "Ornamental Fishes", "Orthodox Church", "Outdoor Activities", "Paganism", 
  "Painting Rooms", "Paintings", "Paleontology", "Paper", "Paralympic Games", 
  "Parent-Child Relationship", "Parenting", "Parrots", "Partnership", "Party Games", 
  "Patio", "Pearls", "Pediatrics", "People", "Performing Arts", "Periods of Art", 
  "Personal Development", "Personal Finance", "Pet Birds", "Philately", "Phonics", 
  "Photographers", "Photography Techniques", "Photojournalism", "Pigeons", "Pilgrimage", 
  "Pistols", "Plants", "Plays", "Poetry", "Police Units", "Political Extremism", 
  "Political History", "Political Ideologies", "Political Parties", "Political Science", 
  "Political Theory", "Popes", "Pop Music", "Pop Stars", "Popular Culture", "Popular Media", 
  "Popular Medicine", "Popular Philosophy", "Popular Psychology", "Popular Science", 
  "Portrait Photography", "Portuguese Cuisine", "Positive Thinking", "Pottery", 
  "Practical Skills", "Pregnancy", "Pre-Romanesque Architecture", "Presbyterianism", 
  "Preschool", "Presentation", "Presents", "Preserving", "Princesses", "Print Art", 
  "Product Design", "Professional Development", "Professional Finance", "Professions", 
  "Programming Languages", "Property", "Protestantism", "Proverbs", "Puberty", 
  "Public Speaking", "Pudding", "Pulps", "Puzzles", "Quackery", "Quick Meals", 
  "Quilting", "Quizzes", "Quotations", "R&B", "Racquet Sports", "Radio", "Railway", 
  "Rap", "Real Estate", "Recreation", "Recruitment Tests", "Redevelopment", "Reference", 
  "Reform Style", "Refurbishment", "Regency", "Regional Cooking", "Regional History", 
  "Relations", "Relationships", "Religions of the Ancient World", "Religious History", 
  "Renaissance", "Renewable Energy", "Renting", "Repairing", "Reptiles", "Restoration", 
  "Retirement Planning", "Revolution Architecture", "Revolvers", "Rhetoric", "Rifles", 
  "Rights", "Rituals", "Road Vehicles", "Rock Climbing", "Rock Music", "Role Playing Games", 
  "Rollerblading", "Roman Architecture", "Romanesque Art", "Roman Wars", "Royalty", 
  "Rugby", "Running", "Russian Cuisine", "Saints", "Salary", "Sales", "Satire", "Sauces", 
  "Scandinavian Cuisine", "Schlager Music", "School", "Science", "Scouting", "Scrapbooking", 
  "Screenplays", "Script/Play", "Scuba & Snorkeling", "Sculpture", "Seafood", "Security", 
  "Self-Defence", "Self-Esteem", "Self-Help", "Self-Improvement", "Self-Management", 
  "Sermons", "Setting up Business", "Sewing", "Sexual Abuse", "Sheep", "Ships", 
  "Shooting Sport", "Shrubs", "Sign Language", "Sikhism", "Silent Movies", "Silhouettes", 
  "Single Parenting", "Skateboarding", "Skating", "Small Animals", "Small Business", 
  "Snooker, Pool & Billiards", "Soccer", "Social Activists", "Social History", 
  "Social Issues", "Social Sciences", "Social Services", "Social Situations", "Society", 
  "Software Packages", "Songbirds", "Soul Music", "Soundtracks", "Soups", 
  "South American Cuisine", "South European Cuisine", "Spacecraft", "Space Exploration", 
  "Spanish Cuisine", "Speech Disorders", "Spirits", "Spooky Stories", "Sport Diving", 
  "Sports Photography", "Sports Science", "Stamps", "Stews", "Stock Exchange", "Stocks", 
  "Submarines", "Sub-Saharan African Cuisine", "Success", "Sudoku", "Sugar-Free Cooking", 
  "Supernatural", "Surgery", "Surrealism", "Survival", "Suspense", "Swimming", 
  "Swiss Cuisine", "Table Culture", "Taoism", "Tarot", "Task Force", "Tasmanian Tiger", 
  "Taxes", "Tea", "Teaching", "Technology", "Telecommunications Engineering", "Television", 
  "Tennis", "Terrorism", "Tests", "Textiles", "Theatre", "Theology", "Therapy", 
  "Thinking Techniques", "Thriller", "Time Management", "Time Travel", "Tobacciana", 
  "Topography", "Track and Field (Athletics)", "Tractors", "Trading Cards", 
  "Traditional Folk Music", "Training", "Trains", "Transport Technology", "Travel Guide", 
  "Travel with Children", "Travel Writing", "Treatments", "Trees", "Trivia", "True Crime", 
  "True Military Stories", "True Stories", "Tuning", "Turkish Cuisine", "TV Game Shows", 
  "TV Shows", "UFOlogy", "Underwater Photography", "United States Armed Forces", 
  "Vampires", "Vegan Cooking", "Vegetarian Cooking", "Vehicle Maintenance", 
  "Veterinary Medicine", "Video Games", "Video Processing", "Vietnam War", "Visualisation", 
  "Vocational Skills", "Wallpaper", "War", "Warfare", "War Photography", "Water Sports", 
  "Waterways", "Weapons", "Weather", "Web Development", "Weddings", "Weightlifting", 
  "Weight Loss", "Weight Watchers", "Welfare", "Wellness", "Wellness Holidays", 
  "Werewolves", "Western European Cuisine", "Westerns", "Wholefood", "Wicca", 
  "Wilderness", "Wild Flowers", "Wildlife", "Window Color", "Windows", "Wines", 
  "Winter Sports", "Witchcraft", "Women's Studies", "Women Sleuths", "Woodwork", 
  "Wordsearch", "Work-Life-Balance", "World Championship", "World History", 
  "World War I", "World War II", "Wrestling", "Writing", "Yoga", "Youth Work", "Zombies"
];

/**
 * Search topics by keyword
 * @param {string} keyword - Search term
 * @returns {string[]} - Matching topics
 */
function searchTopics(keyword) {
  if (!keyword || keyword.trim() === '') return VALID_EBAY_TOPICS;
  
  const searchTerm = keyword.toLowerCase();
  return VALID_EBAY_TOPICS.filter(topic => 
    topic.toLowerCase().includes(searchTerm)
  );
}

/**
 * Get topics that start with the given keyword
 * @param {string} keyword - Search term
 * @returns {string[]} - Matching topics
 */
function getTopicsStartingWith(keyword) {
  if (!keyword || keyword.trim() === '') return [];
  
  const searchTerm = keyword.toLowerCase();
  return VALID_EBAY_TOPICS.filter(topic => 
    topic.toLowerCase().startsWith(searchTerm)
  );
}

module.exports = {
  VALID_EBAY_TOPICS,
  searchTopics,
  getTopicsStartingWith
};
