name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'  # Using Node.js 22 as per your setup
          
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
        env:
          CI: false  # Prevents treating warnings as errors
          
      - name: Debug build output
        run: |
          echo "Checking build directory contents:"
          ls -la
          echo "Checking client directory:"
          ls -la client
          echo "Checking client/build directory:"
          if [ -d "client/build" ]; then
            ls -la client/build
            echo "Index.html exists: $(test -f client/build/index.html && echo Yes || echo No)"
          else
            echo "client/build directory not found!"
          fi
          
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "node_modules/*" "client/node_modules/*"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9D004D21C75347BA9806BE4CC163965C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3E0B89EC11F4FED8B068B51CD29FC5B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D13093ED2B8849709EBA5A77FAFC2C21 }}
          
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'book-listing-software-web-app'
          package: .